### ISSUE TITLE
Receiving multiple prompts

### ISSUE THREAD

**Issue by peduarte** [fathomlondon/devlinks-bot#21]
I shared a link and was prompted by the bot several times 😂 

![image](https://user-images.githubusercontent.com/372831/46877442-cb5a8e00-ce38-11e8-9d3a-67ae74fd9402.png)

**Comment by benoitgrelard** [comment]
Yes I noticed this with the production one as well, not sure why, I need to look into it.

**Comment by benoitgrelard** [comment]
I think if Slack doesn't receive an `ok`  200 from us in a timely manner, it resends the event, so that could be what we're seeing here.
