### ISSUE TITLE
Generate one PR per link

### ISSUE THREAD

**Issue by benoitgrelard** [fathomlondon/devlinks-bot#8]
via @peduarte 

👇 

Currently the PR's seems to be batching multiple links, I think it's a nicer design if it creates one PR per link shared.

Why?

- Easier to discard unwanted links
- Less code complexity
- Rely on GH to manage order/conflicts

**Comment by benoitgrelard** [comment]
@petecorreia what do you think about this?

As much as I thought this was a good feature, @peduarte might have a point here.
Shall I make the change?

**Comment by petecorreia** [comment]
Give it a go, see how it feels. I'm thinking that a PR per link is more intuitive
