### ISSUE TITLE
dev development

### ISSUE THREAD

**Issue by benoitgrelard** [fathomlondon/devlinks-bot#9]
I initially worked on this isolation with a ngrok tunnel pointed to my localhost (and the ngrok url configured on the Slack app) and was pointing to a different testing channel id.
This enabled me to work on this without bothering anybody on the `#dev` channel.

I am not sure how to go about enabling developing on this without having to deploy and test the real thing for now. Curious if anybody has ideas?

- Should we have a testing channel for bots?
- Do we need to create a duplicate Slack app (devlinks-bot-dev) to test?

@ibrennan you did some work with Slack bots, did you get into this?

**Comment by ibrennan** [comment]
I created a private channel that I used to test the bot against, and then switched out the channel name when deploying.

I'd suggest storing the channel name in an environment variable, and configuring it on your deployed environment to be `#developer` and something else for local dev.

**Comment by benoitgrelard** [comment]
@ibrennan ok I think targetting a different channel should be easy enough. I'm just trying to think if that's enough. I guess doing it this way, I shouldn't need to have to create a duplicate app?
